"""
Extra targeted coverage tests for agents.py and _core_config.py.

Covers uncovered branches to lift per-file coverage to >=90%:

agents.py:
  - _is_legacy_generator_stub: return False for extra body lines (line 230)
  - _is_legacy_generator_toml_stub: TOMLDecodeError path (lines 263-264),
    not-a-dict / empty-dict path (line 266)
  - _render_agent_lines: context_window=max warning when no model_id (line 1132)
  - _is_agent_installed: windsurf legacy workflow detection (line 2047),
    cursor legacy agents/commands detection (line 2062),
    claude legacy skills dir with cypilot- prefix (lines 2075-2077),
    claude legacy agents dir with cypilot- prefix (lines 2080-2082),
    copilot legacy copilot-instructions.md OSError (lines 2095-2096),
    copilot legacy cypilot.prompt.md (line 2104),
    openai legacy .cypilot-installed marker (line 2122),
    openai legacy codex agents with follow-link (lines 2125-2132)
  - _cleanup_legacy_skill_dirs: OSError on iterdir (lines 2412-2413),
    non-dir entry skipped (line 2416), rglob OSError (lines 2422-2423),
    empty files list -> all_pure=False (line 2424),
    file read OSError -> all_pure=False (lines 2428-2430),
    legacy is_legacy=True _is_legacy_generator_stub check (lines 2440-2443),
    non-legacy _is_pure_studio_generated check (lines 2444-2447),
    all_pure=False skip (lines 2448-2449), dry_run append (lines 2451-2452),
    shutil.rmtree and OSError on unlink (lines 2454-2459)

_core_config.py:
  - load_core_config: OSError / ValueError exception handler (lines 30-32)
    using the correct .cf adapter directory
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch, MagicMock

# conftest.py already inserts skills/studio/scripts, so no manual sys.path needed


class TestCoreConfigExceptionBranchStudio(unittest.TestCase):
    """Cover lines 30-32 in _core_config.py (studio version, .cf adapter dir)."""

    def test_load_returns_empty_on_os_error(self):
        from studio.commands._core_config import load_core_config
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            config_dir = root / ".cf" / "config"
            config_dir.mkdir(parents=True)
            (config_dir / "core.toml").write_text("[project]\n", encoding="utf-8")
            with patch("builtins.open", side_effect=OSError("permission denied")):
                result = load_core_config(root)
        self.assertEqual(result, {})

    def test_load_returns_empty_on_invalid_toml(self):
        from studio.commands._core_config import load_core_config
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            config_dir = root / ".cf" / "config"
            config_dir.mkdir(parents=True)
            # Write bytes that are invalid TOML (causes ValueError from tomllib)
            (config_dir / "core.toml").write_bytes(b"invalid = [[[\x00")
            result = load_core_config(root)
        self.assertEqual(result, {})


class TestIsLegacyGeneratorStubReturnFalse(unittest.TestCase):
    """Cover line 230 in agents.py (_is_legacy_generator_stub returns False)."""

    def test_extra_body_line_returns_false(self):
        from studio.commands.agents import _is_legacy_generator_stub
        # Content has a follow-link with legacy template AND a marker, but
        # also has an extra non-blank line that is not a follow-link or H1 slug.
        content = (
            "---\nname: test\n---\n"
            "<!-- Generated by cf agents -- do not edit -->\n"
            "ALWAYS open and follow `{cypilot_path}/.core/SKILL.md`\n"
            "This extra line should cause return False.\n"
        )
        result = _is_legacy_generator_stub(content)
        self.assertFalse(result)


class TestIsLegacyGeneratorTomlStub(unittest.TestCase):
    """Cover TOML error / empty-dict paths in _is_legacy_generator_toml_stub."""

    def test_toml_decode_error_returns_false(self):
        from studio.commands.agents import _is_legacy_generator_toml_stub
        # Has marker but is invalid TOML -> TOMLDecodeError -> return False
        content = (
            "# Generated by cf agents -- do not edit\n"
            "name = \"test\"\n"
            "developer_instructions = [[[invalid\n"
        )
        result = _is_legacy_generator_toml_stub(content)
        self.assertFalse(result)

    def test_empty_toml_dict_returns_false(self):
        from studio.commands.agents import _is_legacy_generator_toml_stub
        # Has marker but parses to empty dict -> return False
        content = "# Generated by cf agents -- do not edit\n"
        result = _is_legacy_generator_toml_stub(content)
        self.assertFalse(result)

    def test_valid_toml_with_only_allowed_keys_returns_true(self):
        from studio.commands.agents import _is_legacy_generator_toml_stub
        content = (
            "# Generated by cf agents -- do not edit\n"
            'name = "cf-codegen"\n'
            'description = "A test agent"\n'
            'developer_instructions = "ALWAYS open and follow `{cypilot_path}/.core/SKILL.md`"\n'
        )
        result = _is_legacy_generator_toml_stub(content)
        self.assertTrue(result)


class TestAgentTemplateClaudeContextWindowMaxWarning(unittest.TestCase):
    """Cover line 1132: context_window=max warning when no model_id resolved."""

    def test_context_window_max_no_model_warns(self):
        from studio.commands.agents import _agent_template_claude
        import io

        # Use cf:inherit so _resolve_model_id returns None, triggering the warning
        agent = {
            "name": "test-agent",
            "description": "A test agent",
            "mode": "readwrite",
            "isolation": False,
            "model": "cf:inherit",
            "context_window": "max",
            "reasoning_effort": None,
            "provider": "anthropic",
            "role": "any",
            "target": "any",
        }

        stderr_capture = io.StringIO()
        with patch("sys.stderr", stderr_capture):
            lines = _agent_template_claude(agent)
        self.assertIn("context_window=max has no effect", stderr_capture.getvalue())


class TestIsAgentInstalledLegacyPaths(unittest.TestCase):
    """Cover legacy fallback detection paths in _is_agent_installed."""

    def test_windsurf_legacy_workflow_cypilot_file(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            wf_dir = root / ".windsurf" / "workflows"
            wf_dir.mkdir(parents=True)
            (wf_dir / "cypilot-analyze.md").write_text("# Cypilot Analyze\n", encoding="utf-8")
            result = _is_agent_installed("windsurf", root)
        self.assertTrue(result)

    def test_windsurf_legacy_workflow_cypilot_md(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            wf_dir = root / ".windsurf" / "workflows"
            wf_dir.mkdir(parents=True)
            (wf_dir / "cypilot.md").write_text("# Cypilot\n", encoding="utf-8")
            result = _is_agent_installed("windsurf", root)
        self.assertTrue(result)

    def test_cursor_legacy_cypilot_agents_dir(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            agents_dir = root / ".cursor" / "agents"
            agents_dir.mkdir(parents=True)
            (agents_dir / "cypilot-codegen.md").write_text(
                "ALWAYS open and follow `{cypilot_path}/.core/SKILL.md`\n",
                encoding="utf-8",
            )
            result = _is_agent_installed("cursor", root)
        self.assertTrue(result)

    def test_cursor_legacy_cypilot_commands_dir(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            cmd_dir = root / ".cursor" / "commands"
            cmd_dir.mkdir(parents=True)
            (cmd_dir / "cypilot-generate.md").write_text(
                "ALWAYS open and follow `{cypilot_path}/.core/SKILL.md`\n",
                encoding="utf-8",
            )
            result = _is_agent_installed("cursor", root)
        self.assertTrue(result)

    def test_claude_legacy_skills_dir_with_cypilot_prefix(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skills_dir.mkdir(parents=True)
            (skills_dir / "cypilot-analyze").mkdir()
            result = _is_agent_installed("claude", root)
        self.assertTrue(result)

    def test_claude_legacy_agents_dir_with_cypilot_prefix(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            agents_dir = root / ".claude" / "agents"
            agents_dir.mkdir(parents=True)
            (agents_dir / "cypilot-codegen.md").write_text("# Codegen\n", encoding="utf-8")
            result = _is_agent_installed("claude", root)
        self.assertTrue(result)

    def test_copilot_legacy_instructions_os_error(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            ci_dir = root / ".github"
            ci_dir.mkdir(parents=True)
            ci_path = ci_dir / "copilot-instructions.md"
            ci_path.write_text("# Constructor Studio\nsome content\n", encoding="utf-8")
            # Patch read_text to raise OSError so the except path is covered
            with patch("pathlib.Path.read_text", side_effect=OSError("permission denied")):
                result = _is_agent_installed("copilot", root)
        # Should fall through to False (or check prompts) without raising
        self.assertIsInstance(result, bool)

    def test_copilot_legacy_cypilot_prompt_file(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            prompts_dir = root / ".github" / "prompts"
            prompts_dir.mkdir(parents=True)
            (prompts_dir / "cypilot.prompt.md").write_text("# Studio\n", encoding="utf-8")
            result = _is_agent_installed("copilot", root)
        self.assertTrue(result)

    def test_openai_legacy_cypilot_installed_marker(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            codex_dir = root / ".codex"
            codex_dir.mkdir(parents=True)
            (codex_dir / ".cypilot-installed").write_text("", encoding="utf-8")
            result = _is_agent_installed("openai", root)
        self.assertTrue(result)

    def test_openai_legacy_codex_agent_with_follow_link(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            agents_dir = root / ".codex" / "agents"
            agents_dir.mkdir(parents=True)
            (agents_dir / "cf-codegen.toml").write_text(
                "# Generated by cf agents -- do not edit\n"
                'name = "cf-codegen"\n'
                'developer_instructions = "ALWAYS open and follow `{cypilot_path}/.core/SKILL.md`"\n',
                encoding="utf-8",
            )
            result = _is_agent_installed("openai", root)
        self.assertTrue(result)

    def test_openai_legacy_codex_agent_unreadable_file(self):
        from studio.commands.agents import _is_agent_installed
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            agents_dir = root / ".codex" / "agents"
            agents_dir.mkdir(parents=True)
            agent_file = agents_dir / "cf-codegen.md"
            agent_file.write_text("some content\n", encoding="utf-8")
            # Make the file raise UnicodeDecodeError on read_text
            original_read_text = Path.read_text

            def patched_read_text(self, *args, **kwargs):
                if self == agent_file:
                    raise UnicodeDecodeError("utf-8", b"", 0, 1, "invalid")
                return original_read_text(self, *args, **kwargs)

            with patch("pathlib.Path.read_text", patched_read_text):
                result = _is_agent_installed("openai", root)
        # Should not raise; result is False (no follow link found)
        self.assertFalse(result)


class TestCleanupLegacySkillDirs(unittest.TestCase):
    """Cover _cleanup_legacy_skill_dirs paths."""

    def _make_legacy_skill_content(self, agent_name: str) -> str:
        """Return content that _is_legacy_generator_stub accepts."""
        return (
            "---\nname: {}\ndescription: Test\n---\n".format(agent_name)
            + "<!-- Generated by cf agents -- do not edit -->\n"
            "ALWAYS open and follow `{cypilot_path}/.core/SKILL.md`\n"
        )

    def test_iterdir_os_error_is_skipped(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skills_dir.mkdir(parents=True)
            original_iterdir = Path.iterdir

            def patched_iterdir(self):
                if self == skills_dir:
                    raise OSError("permission denied")
                return original_iterdir(self)

            with patch("pathlib.Path.iterdir", patched_iterdir):
                result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True)
        self.assertEqual(result, [])

    def test_non_dir_entry_skipped(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skills_dir.mkdir(parents=True)
            # Create a file (not a directory) with a cypilot prefix
            (skills_dir / "cypilot-readme.md").write_text("# README\n", encoding="utf-8")
            result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True, remove_cypilot=True)
        self.assertEqual(result, [])

    def test_rglob_os_error_is_skipped(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            (skill_dir / "SKILL.md").write_text(
                self._make_legacy_skill_content("cypilot-analyze"), encoding="utf-8",
            )
            original_rglob = Path.rglob

            def patched_rglob(self, pattern):
                if self == skill_dir:
                    raise OSError("permission denied")
                return original_rglob(self, pattern)

            with patch("pathlib.Path.rglob", patched_rglob):
                result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True)
        self.assertEqual(result, [])

    def test_empty_skill_dir_skipped(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            # Empty directory: no files, so all_pure = bool([]) = False
            result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True, remove_cypilot=True)
        self.assertEqual(result, [])

    def test_file_read_error_causes_all_pure_false(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            skill_file = skill_dir / "SKILL.md"
            skill_file.write_text(
                self._make_legacy_skill_content("cypilot-analyze"), encoding="utf-8",
            )
            original_read_text = Path.read_text

            def patched_read_text(self, *args, **kwargs):
                if self == skill_file:
                    raise OSError("permission denied")
                return original_read_text(self, *args, **kwargs)

            with patch("pathlib.Path.read_text", patched_read_text):
                result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True)
        self.assertEqual(result, [])

    def test_legacy_dir_with_pure_content_dry_run_appended(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            (skill_dir / "SKILL.md").write_text(
                self._make_legacy_skill_content("cypilot-analyze"), encoding="utf-8",
            )
            result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True, remove_cypilot=True)
        self.assertIn(".claude/skills/cypilot-analyze", result)

    def test_legacy_dir_with_user_content_not_deleted(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            # User-authored content: not a pure generator stub
            (skill_dir / "SKILL.md").write_text(
                "---\nname: cypilot-analyze\ndescription: My custom skill\n---\n"
                "This is user-authored content.\n",
                encoding="utf-8",
            )
            result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True)
        self.assertEqual(result, [])

    def test_non_legacy_dir_with_user_content_not_deleted(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            # studio- prefix (non-legacy) with user content
            skill_dir = skills_dir / "studio"
            skill_dir.mkdir(parents=True)
            (skill_dir / "SKILL.md").write_text(
                "---\nname: studio\ndescription: User edited\n---\n"
                "User has customized this file.\n"
                "ALWAYS open and follow `{cf-studio-path}/.core/SKILL.md`\n",
                encoding="utf-8",
            )
            result = _cleanup_legacy_skill_dirs("claude", root, dry_run=True)
        self.assertEqual(result, [])

    def test_legacy_dir_actual_delete(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            (skill_dir / "SKILL.md").write_text(
                self._make_legacy_skill_content("cypilot-analyze"), encoding="utf-8",
            )
            result = _cleanup_legacy_skill_dirs("claude", root, dry_run=False, remove_cypilot=True)
        self.assertIn(".claude/skills/cypilot-analyze", result)
        self.assertFalse(skill_dir.exists())

    def test_delete_os_error_continues(self):
        from studio.commands.agents import _cleanup_legacy_skill_dirs
        import shutil
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / ".claude" / "skills"
            skill_dir = skills_dir / "cypilot-analyze"
            skill_dir.mkdir(parents=True)
            (skill_dir / "SKILL.md").write_text(
                self._make_legacy_skill_content("cypilot-analyze"), encoding="utf-8",
            )
            with patch("shutil.rmtree", side_effect=OSError("permission denied")):
                result = _cleanup_legacy_skill_dirs("claude", root, dry_run=False, remove_cypilot=True)
        # OSError is swallowed with a warning — not appended to result
        self.assertEqual(result, [])


if __name__ == "__main__":
    unittest.main()
